# Generated by Django 5.1.6 on 2025-02-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_staff_wards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wards',
            new_name='ward',
        ),
    ]
